// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

import type { Database } from './types';

const SUPABASE_URL = 'https://xvzrvzhmppkjydvefcnt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2enJ2emhtcHBranlkdmVmY250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTA4NjksImV4cCI6MjA2NTQ4Njg2OX0.Y742H_X0RRDXVcwj6vKmnimORqDLDHgWj17H_KHtwJ8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
